### ISSUE TITLE
rtl8723d_config-OBDA8723.bin

### ISSUE THREAD

**Issue by drosdeck** [lwfinger/rtl8723ds#12]
where can I find rtl8723d_config-OBDA8723.bin ?

I'm using debian 10 and i got the message

[   11.241601] Bluetooth: hci0: RTL: loading rtl_bt/rtl8723d_fw.bin
[   11.246773] Bluetooth: hci0: RTL: loading rtl_bt/rtl8723d_config-OBDA8723.bin
[   11.246825] bluetooth hci0: Direct firmware load for rtl_bt/rtl8723d_config-OBDA8723.bin failed with error -2
[   11.246830] Bluetooth: hci0: RTL: mandatory config file rtl_bt/rtl8723d_config not found

**Comment by lwfinger** [comment]
Remember that I do not do BT, and I have no idea what that special firmware should be doing, but it is in the official linux-firmware git repository. Ask Debian why it is not available.
