### ISSUE TITLE
License

### ISSUE THREAD

**Issue by benthetechguy** [lwfinger/rtl8723ds#16]
What license is this source code released under?

**Comment by lwfinger** [comment]
Every file has a header that contains the following:

 * This program is free software; you can redistribute it and/or modify it
 * under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.

The license is GPLv2.

**Comment by benthetechguy** [comment]
Ah, I didn't check for any headers; I was just looking for a LICENSE or COPYING file. Thanks!
