### ISSUE TITLE
Can it support kernel v6.1.1?

### ISSUE THREAD

**Issue by ppmarc07** [lwfinger/rtl8723ds#39]
Dear lwfinger,
 This rtl8723ds driver can it support kernel v6.1.1?Or do you have a plan to support rtl8723ds to kernel v6.1
 thanks!

**Comment by GiyoMoon** [comment]
Hey, this driver works with kernel up to 6.4, I've tried it. But the rtl8723ds driver is now also included in the rtw88 repo (https://github.com/lwfinger/rtw88), lwfinger suggested me to switch to that and it also works with 6.x kernels :)

**Comment by lwfinger** [comment]
The driver will never be built into kernels older than v6.5 - note that 6.4 will not be released for about one month. That is the reason that repo rtw88 exists - namely to provide up to date drivers for older kernels.

**Comment by ppmarc07** [comment]
ok，thanks
