### ISSUE TITLE
MangoPi Pro driver not detecting rtl8723ds

### ISSUE THREAD

**Issue by moleisking** [lwfinger/rtl8723ds#40]
After installation, the iwconfig shows no new wlan0. An example of the chip is at https://www.fn-link.com/6223A-SRD-Wi-Fi-Module-pd45576170.html

**Comment by moleisking** [comment]
An example of the chip is at https://www.fn-link.com/6223A-SRD-Wi-Fi-Module-pd45576170.html

**Comment by lwfinger** [comment]
I am not going to make any changes in this vendor driver.

Try https://github.com/lwfinger/rtw88.git. If your device still does not show up there, then we will debug it in that repo.
