### ISSUE TITLE
RTL8723DS Bluetooth

### ISSUE THREAD

**Issue by briansune** [lwfinger/rtl8723ds#42]
@lwfinger 

I am not sure but are there any driver can run UART RTL8723DS bluetooth with H4?
Or RTL8723DS only use H5?
For USB it can run internal kernel supplied bluetooth driver.
But for RTL8723DS I am lost.

Thank you

**Comment by lwfinger** [comment]
According to the datasheet, the RTL8723DS has an H4.2 Bluetooth interface. That should be handled by the hci_uart kernel module. That driver does not have any specific Realtek version. I have no idea if that is because it is driven by the general code, or if no one has ever looked at the serial BT devices from Realtek. In any case, I am not able to help with this issue.

**Comment by briansune** [comment]
@lwfinger 

Okay, thank you again.
I am trying out the UART 3-wire.

**Comment by lwfinger** [comment]
You had a clock question that seems to be missing now. What frequency are you supplying to pin 15 of the chip? The only thing I found in the driver is the option of 26 MHz, but that option is disabled, and I think it applies to the output on pin 16.

**Comment by briansune** [comment]
@lwfinger 

Crystal (XTAL) 24MHz.
If 26MHz is placed the WIFI will not work.
XTAL uses both 15 and 16.

I might be wrong but what frequency it uses when the EFUSE default is loaded?

**Comment by briansune** [comment]
@lwfinger 

Or you are proposing BT and  WIFI is using different XTAL settings?

**Comment by briansune** [comment]
@lwfinger 

I had conducted an experiment with the 26MHz define added in the hal_init OLD driver file.
The WIFI no longer work under 26MHz XTAL nor 24MHz.
However when removing the define flag and use 24MHz WIFI is working normal with no stability problem.

So I am confused.

**Comment by lwfinger** [comment]
According to the datasheet, pin 16 is an output. What do you mean "XTAL uses both 15 and 16"?

The driver does not set the frequency - that comes from the XTAL. Figure 2 shows frequencies of 52, 48, 40, 38.4, 27, 26, 25, 24, 20, 19.2, 17.664, 16, 14.318, 13 and 12MHz as selectable

**Comment by briansune** [comment]
@lwfinger 

I guess you are not too familiar with hardware.
![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/9563403e-e895-4c62-88bb-ac03365da86c)


If oscillator chip is used, only pin 15 will be used.
But when crystal-oscillator aka XTAL it is a passive component require both 15 and 16.
This is a very basic hardware or clock hardware design.
Two methods are allowed oscillator single-end frequency or passive crystal.

The driver do able to set the frequency with load-capacitor when XTAL is used as there are load-cap adjustment.
But such variation is based to the fundamental XTAL frequency. In example 24MHz is low then it can adjust back to 24MHz.
And the PLL aka phase-lock-loop also require to program with correct registers parameter.
It is true that the chip accept multiple XTAL or OSC input but the chip itself had no internal reference clock to detect the input frequency so register program is need to tell the chip what frequency is using.
And the PLL lock will not happen unless the register is program correct.

Thank you

**Comment by briansune** [comment]
@lwfinger 

And if XTAL 24MHz is wrongly apply from first place it will not able to run WIFI aka all nmcli scan and connect.
But I am not software-guy so when define 26MHz is added XTAL changed to 26MHz WIFI is not working, which means the driver setting is incorrect.

Thank you

**Comment by briansune** [comment]
@lwfinger 

I discover that the BT is behaving very bizarre.
Channel 1 is TX Channel 0 is RX
![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/a9d011c5-5528-45b2-8fce-6ec20c0766df)
![image](https://github.com/lwfinger/rtl8723ds/assets/29487339/a839fab4-2a00-4178-b2cd-8a38b4000a11)

It is clear that the RX BAUD RATE is very wrong.
@lwfinger 

Do the driver affect the internal BT settings?

Thank you

**Comment by lwfinger** [comment]
Who knows? I am not an expert on BT, particularly so for serial BT.

**Comment by briansune** [comment]
@lwfinger 

So to your understanding, WIFI driver and BT driver is individual.
But you have no idea how these driver could affect each other?

Thank you

**Comment by lwfinger** [comment]
Yes, the wifi and BT drivers are distinct. The only connection between the two devices is that they share the 2.4 GHz radio, and the wifi driver needs to handle the coexistence of the two radio streams.

The other thing is that the two drivers share some clocks because they are in the same package.

**Comment by briansune** [comment]
@lwfinger 

Appreciate the update. Meanwhile, do the rtk_hciattach binary make any different?
For my understanding that repository is the driver insert aka ****.ko
But to use the driver rtk_hciattach is needed.
And rtk_hciattach is seek from https://github.com/edision-open/LINUX_BT_DRIVER_RTL8723D.git

**Comment by lwfinger** [comment]
Again, I have no direct knowledge, but I think hci_uart.ko from my repo should do.

**Comment by briansune** [comment]
@lwfinger 

Okay, I will give it a try first and lets see the result.
Do understand you are not BT developers.
But I guess for UART is should be less problem than complex protocol like SDIO or USB.
And turns out not the case =[

**Comment by briansune** [comment]
@lwfinger 

I got some of these error messages:

realtek_bluetooth/btusb.c:842:10: error: 'struct hci_dev' has no member named 'reset'
  842 |  if (hdev->reset) {

realtek_bluetooth/btusb.c:1240:4: error: implicit declaration of function 'hci_cmd_sync_cancel'; did you mean 'hci_cmd_sync'? [-Werror=implicit-function-declaration]
 1240 |    hci_cmd_sync_cancel(hdev, -err);
      |    ^~~~~~~~~~~~~~~~~~~
      |    hci_cmd_sync

realtek_bluetooth/btusb.c:3869:10: error: 'HCI_QUIRK_BROKEN_ENHANCED_SETUP_SYNC_CONN' undeclared (first use in this function)
 3869 |  set_bit(HCI_QUIRK_BROKEN_ENHANCED_SETUP_SYNC_CONN, &hdev->quirks);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


I need to do some modification for kernel 5.4?

**Comment by briansune** [comment]
@lwfinger 

I used the git link I attached and finally got it works.
Turns out all about 1 single resistor is cold joined.
And what you guess, exactly the BT power-down pull high.
OMG 

Again thank you for the guide and great work to Earth =]
