### ISSUE TITLE
Merge the driver in mainline Linux

### ISSUE THREAD

**Issue by FedericoCeratto** [lwfinger/rtl8723ds#48]
I see kernel 6.7.12 lists rtl8723ds in `sun20i-d1-mangopi-mq-pro.dts`.
Any chance the driver will be merged in to mainline Linux soon?

Thanks!

**Comment by FedericoCeratto** [comment]
It appears support has been added as part of the rtw88 driver, is that correct?
https://lore.kernel.org/all/20230522202425.1827005-5-martin.blumenstingl@googlemail.com/

**Comment by lwfinger** [comment]
Yes, the SDIO implementation was added to wireless-next with commit 65371a3f14e7 on   Wed Apr 5 22:07:22 2023 +0200.
It is part of kernel 6.4; however, there have been a number of fixes since, and I would recommend using kernel 6.7 or 6.8.
